name: 'Policy-as-Code: Composite Action Runner'

# Controls when the action will run. Triggers the workflow on push request
# events but only for the non-master branch
on:
  workflow_dispatch:
    inputs:
     keypair:
      description: 'SSH Key Pair'
      required: true
jobs:
  IntialAction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: CloudFormation Guard Check
        id: docker-cfn
        uses: jstmcneil/PaC-CFN-Deploy@1.1
        with:
          rule-file-name: 'ruleset_migrated.guard'
          app_CI_key: 'TES'
          ms-teams-webhook: ''
          color_style: 'dark'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          template: my_local_template.yml
          parameter-overrides: "KeyName=${{ github.event.inputs.keypair }}"
