# This workflow is a template for working with an aws managed repository

name: Sample AWS github action

# Controls when the action will run. Triggers the workflow on push request
# events but only for the non-master branch
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
     - '*'
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: us-east-2
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Test Stack Creation
          template: my_local_template.yml
        
