# This workflow is a template for working with an aws managed repository

name: CFN-Guard Deployment Prototype

# Controls when the action will run. Triggers the workflow on push request
# events but only for the non-master branch
on:
  workflow_dispatch:
    inputs:
       keypair:
        description: 'SSH Key Pair'
        required: true
jobs:
  IntialAction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Private Action
        id: action-get
        uses: actions/checkout@v2
        with:
          repository: jstmcneil/Policy-as-Code-Action
          persist-credentials: false
          path: ./.github/actions/Policy-as-Code
      - name: CloudFormation Guard Check
        id: docker-cfn
        uses: ./.github/actions/Policy-as-Code
        with:
          rule-file-name: 'ruleset_migrated.guard'
          app_CI_key: 'TES'
          ms-teams-webhook: ''
          color_style: 'dark'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: creds
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: Testing-EC2-Stack
          template: my_local_template.yml
          parameter-overrides: "KeyName=${{ github.event.inputs.keypair }}"
        
