on:
  workflow_dispatch:
    inputs:
       template:
        description: 'Path to template being deployed.'
        required: true
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: jstmcneil/javascript-action-attach-git@1.1
        with:
          template-name: ${{ github.event.inputs.template }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
