name: 'Policy-as-Code Deploy'

# Controls when the action will run. Triggers the workflow on push request
# events but only for the non-master branch
on:
  workflow_dispatch:
    inputs:
     keypair:
      description: 'SSH Key Pair'
      required: true
jobs:
  CFN-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: CloudFormation Guard Check
        id: docker-cfn
        uses: jstmcneil/PaC-Deploy-wiz@1.2
        with:
          name: Testing-EC2-Stack-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          wiz_cli_key: ${{ secrets.wiz_cli_key }}
          wiz_secret_key: ${{ secrets.wiz_secret_key }}
          template: my_local_template.yml
          parameter-overrides: "KeyName=${{ github.event.inputs.keypair }}"
